{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2020-22218",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-787"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://github.com/libssh2/libssh2/pull/476",
        "name": "https://github.com/libssh2/libssh2/pull/476",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking",
          "Patch"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00006.html",
        "name": "[debian-lts-announce] 20230908 [SECURITY] [DLA 3559-1] libssh2 security update",
        "refsource": "MLIST",
        "tags": []
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20231006-0002/",
        "name": "https://security.netapp.com/advisory/ntap-20231006-0002/",
        "refsource": "CONFIRM",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "An issue was discovered in function _libssh2_packet_add in libssh2 1.10.0 allows attackers to access out of bounds memory."
      }
    ]
  }
}