{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2021-32029",
    "ASSIGNER": "secalert@redhat.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://www.postgresql.org/support/security/CVE-2021-32029/",
        "name": "https://www.postgresql.org/support/security/CVE-2021-32029/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1956883",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1956883",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20211112-0003/",
        "name": "https://security.netapp.com/advisory/ntap-20211112-0003/",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "A flaw was found in postgresql. Using an UPDATE ... RETURNING command on a purpose-crafted table, an authenticated database user could read arbitrary bytes of server memory. The highest threat from this vulnerability is to data confidentiality."
      }
    ]
  }
}