{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2024-24680",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "NVD-CWE-noinfo"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://groups.google.com/forum/#%21forum/django-announce",
        "name": "https://groups.google.com/forum/#%21forum/django-announce",
        "refsource": "",
        "tags": [
          "Permissions Required"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/5.0/releases/security/",
        "name": "https://docs.djangoproject.com/en/5.0/releases/security/",
        "refsource": "",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/",
        "refsource": "",
        "tags": [
          "Release Notes"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX/",
        "name": "FEDORA-2024-5c7fb64c74",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6/",
        "name": "FEDORA-2024-2ec03ca8cb",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D/",
        "name": "FEDORA-2024-84fbbbb914",
        "refsource": "",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings."
      }
    ]
  }
}