{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2020-4580",
    "ASSIGNER": "psirt@us.ibm.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "NVD-CWE-noinfo"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://www.ibm.com/support/pages/node/6334705",
        "name": "https://www.ibm.com/support/pages/node/6334705",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/184439",
        "name": "ibm-datapower-cve20204580-dos (184439)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "IBM DataPower Gateway 2018.4.1.0 through 2018.4.1.12 could allow a remote attacker to cause a denial of service by sending a specially crafted a JSON request with invalid characters. IBM X-Force ID: 184439."
      }
    ]
  }
}