{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2011-4213",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-264"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "http://code.google.com/p/googleappengine/wiki/SdkReleaseNotes",
        "name": "http://code.google.com/p/googleappengine/wiki/SdkReleaseNotes",
        "refsource": "MISC",
        "tags": [
          "Patch"
        ]
      },
      {
        "url": "http://blog.watchfire.com/files/googleappenginesdk.pdf",
        "name": "http://blog.watchfire.com/files/googleappenginesdk.pdf",
        "refsource": "MISC",
        "tags": [
          "Exploit"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/71062",
        "name": "google-apps-osmodule-priv-esc(71062)",
        "refsource": "XF",
        "tags": [
          "VDB Entry"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "The sandbox environment in the Google App Engine Python SDK before 1.5.4 does not properly prevent use of the os module, which allows local users to bypass intended access restrictions and execute arbitrary commands via a file_blob_storage.os reference within the code parameter to _ah/admin/interactive/execute, a different vulnerability than CVE-2011-1364."
      }
    ]
  }
}