{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2019-25010",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-843"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://rustsec.org/advisories/RUSTSEC-2019-0036.html",
        "name": "https://rustsec.org/advisories/RUSTSEC-2019-0036.html",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/rust-lang-nursery/failure/issues/336",
        "name": "https://github.com/rust-lang-nursery/failure/issues/336",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "An issue was discovered in the failure crate through 2019-11-13 for Rust. Type confusion can occur when __private_get_type_id__ is overridden."
      }
    ]
  }
}